spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_security
    username: postgres
    password: 12345678pP
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
testing:
  app:
    secret: mySecretKey123!
    expiration: 600000 # 10 minutes